"""initial schema

Revision ID: fe7ee0840540
Revises:
Create Date: 2026-08-05 19:44:08.238521

Establishes Alembic as the schema source of truth, replacing the previous
``Base.metadata.create_all()``-on-startup approach against Postgres (still
used for SQLite dev/test — see ``app.database.init_db``). Autogenerated
against an empty SQLite database (no live Postgres instance was available to
generate this against directly) — the column types used throughout
(``sa.String``, ``sa.DateTime(timezone=True)``,
``sa.JSON().with_variant(postgresql.JSONB, 'postgresql')``, etc.) are all
portable SQLAlchemy types that compile correctly per-dialect at apply time,
so this is structurally correct for Postgres. Before trusting this as the
baseline for a real environment: run ``alembic upgrade head`` against a
staging Postgres instance first and diff the resulting schema against
whatever the currently-running production database actually looks like
(``pg_dump --schema-only`` on both, or an equivalent) — any drift means
production has columns/tables this migration doesn't know about yet, which
would need a follow-up migration, not edits to this file.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fe7ee0840540'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_profiles',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('display_name_cipher', sa.Text(), nullable=True),
    sa.Column('display_name_preview', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('settings_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('activities',
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_contact_id'), 'activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_activities_tenant_id'), 'activities', ['tenant_id'], unique=False)
    op.create_index('ix_activities_tenant_type', 'activities', ['tenant_id', 'type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('event_id', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('organizer_email', sa.String(length=255), nullable=False),
    sa.Column('attendee_emails', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_calendar_events_tenant_datetime', 'calendar_events', ['tenant_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_tenant_id'), 'calendar_events', ['tenant_id'], unique=False)
    op.create_index('ix_calendar_events_tenant_provider', 'calendar_events', ['tenant_id', 'provider'], unique=False)
    op.create_table('calendar_oauth_credentials',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_oauth_credentials_tenant_id'), 'calendar_oauth_credentials', ['tenant_id'], unique=False)
    op.create_index('ix_calendar_oauth_tenant_provider', 'calendar_oauth_credentials', ['tenant_id', 'provider'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('domain', sa.String(length=180), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('annual_revenue', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_tenant_email', 'contacts', ['tenant_id', 'email'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('deals',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('close_date', sa.String(length=30), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_tenant_id'), 'deals', ['tenant_id'], unique=False)
    op.create_index('ix_deals_tenant_stage', 'deals', ['tenant_id', 'stage'], unique=False)
    op.create_table('email_analytics',
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('total_emails_received', sa.Integer(), nullable=False),
    sa.Column('total_emails_sent', sa.Integer(), nullable=False),
    sa.Column('emails_with_ai_drafts', sa.Integer(), nullable=False),
    sa.Column('drafts_accepted', sa.Integer(), nullable=False),
    sa.Column('drafts_rejected', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=False),
    sa.Column('total_time_saved_minutes', sa.Float(), nullable=False),
    sa.Column('ai_label_accuracy', sa.Float(), nullable=False),
    sa.Column('ai_priority_detection_accuracy', sa.Float(), nullable=False),
    sa.Column('avg_draft_quality_score', sa.Float(), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_analytics_tenant_date', 'email_analytics', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_email_analytics_tenant_id'), 'email_analytics', ['tenant_id'], unique=False)
    op.create_table('email_consent_logs',
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('marketing_emails', sa.Boolean(), nullable=False),
    sa.Column('transactional_emails', sa.Boolean(), nullable=False),
    sa.Column('ai_processing', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_consent_logs_tenant_id'), 'email_consent_logs', ['tenant_id'], unique=False)
    op.create_table('email_drafts',
    sa.Column('original_email_id', sa.Integer(), nullable=True),
    sa.Column('to_addresses', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('cc_addresses', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('draft_html', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_drafts_tenant_id'), 'email_drafts', ['tenant_id'], unique=False)
    op.create_index('ix_email_drafts_tenant_status', 'email_drafts', ['tenant_id', 'status'], unique=False)
    op.create_table('email_oauth_credentials',
    sa.Column('email_provider', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_oauth_credentials_tenant_id'), 'email_oauth_credentials', ['tenant_id'], unique=False)
    op.create_index('ix_email_oauth_tenant_provider', 'email_oauth_credentials', ['tenant_id', 'email_provider'], unique=False)
    op.create_table('email_sequences',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_emails_sent', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_sequences_tenant_id'), 'email_sequences', ['tenant_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_template', sa.String(length=1024), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('variables', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_tenant_id'), 'email_templates', ['tenant_id'], unique=False)
    op.create_table('emails',
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('thread_id', sa.String(length=512), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_addresses', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('cc_addresses', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('bcc_addresses', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('provider_labels', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_labels', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('attachments_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('email_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('requires_response', sa.Boolean(), nullable=False),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('ix_emails_tenant_from', 'emails', ['tenant_id', 'from_address'], unique=False)
    op.create_index(op.f('ix_emails_tenant_id'), 'emails', ['tenant_id'], unique=False)
    op.create_index('ix_emails_tenant_labels', 'emails', ['tenant_id'], unique=False)
    op.create_index('ix_emails_tenant_status', 'emails', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('platform_message_id', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('thread', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_messages_tenant_id'), 'inbox_messages', ['tenant_id'], unique=False)
    op.create_index('ix_inbox_messages_tenant_status', 'inbox_messages', ['tenant_id', 'status'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('due_date', sa.String(length=30), nullable=True),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('job_executions',
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('job_params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_executions_job_id', 'job_executions', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_executions_tenant_id'), 'job_executions', ['tenant_id'], unique=False)
    op.create_index('ix_job_executions_tenant_status', 'job_executions', ['tenant_id', 'status'], unique=False)
    op.create_table('leads',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=120), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index('ix_leads_tenant_status', 'leads', ['tenant_id', 'status'], unique=False)
    op.create_table('meeting_consent_logs',
    sa.Column('participant_email', sa.String(length=255), nullable=False),
    sa.Column('recording_consent', sa.Boolean(), nullable=False),
    sa.Column('transcript_consent', sa.Boolean(), nullable=False),
    sa.Column('ai_processing_consent', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_consent_logs_tenant_id'), 'meeting_consent_logs', ['tenant_id'], unique=False)
    op.create_table('meeting_preps',
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('briefing', sa.Text(), nullable=False),
    sa.Column('attendee_profiles', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('talking_points', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('potential_questions', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_preps_tenant_id'), 'meeting_preps', ['tenant_id'], unique=False)
    op.create_table('meeting_recaps',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_points', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('decisions_made', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('action_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('follow_up_emails_sent', sa.Boolean(), nullable=False),
    sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_recaps_tenant_id'), 'meeting_recaps', ['tenant_id'], unique=False)
    op.create_table('meeting_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_title', sa.String(length=500), nullable=False),
    sa.Column('default_description', sa.Text(), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_attendee_patterns', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('suggested_agenda', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_templates_tenant_id'), 'meeting_templates', ['tenant_id'], unique=False)
    op.create_table('meetings',
    sa.Column('calendar_event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organizer_id', sa.String(length=255), nullable=False),
    sa.Column('attendees', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('calendar_provider', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.String(length=512), nullable=True),
    sa.Column('conference_url', sa.String(length=1024), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ai_prep_generated', sa.Boolean(), nullable=False),
    sa.Column('prep_notes', sa.Text(), nullable=True),
    sa.Column('meeting_recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('recording_url', sa.String(length=1024), nullable=True),
    sa.Column('recording_provider', sa.String(length=50), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_timestamp_url', sa.String(length=1024), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('key_decisions', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('action_items_extracted', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_tenant_datetime', 'meetings', ['tenant_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_meetings_tenant_id'), 'meetings', ['tenant_id'], unique=False)
    op.create_index('ix_meetings_tenant_status', 'meetings', ['tenant_id', 'status'], unique=False)
    op.create_table('mission_jobs',
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('mission_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tools_to_use', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.String(length=40), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_jobs_tenant_id'), 'mission_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_mission_jobs_tenant_schedule_id', 'mission_jobs', ['tenant_id', 'schedule_id'], unique=False)
    op.create_index('ix_mission_jobs_tenant_status', 'mission_jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('scheduled_posts',
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_tenant_id'), 'scheduled_posts', ['tenant_id'], unique=False)
    op.create_index('ix_scheduled_posts_tenant_platform', 'scheduled_posts', ['tenant_id', 'platform'], unique=False)
    op.create_table('scheduling_preferences',
    sa.Column('work_start_hour', sa.Integer(), nullable=False),
    sa.Column('work_end_hour', sa.Integer(), nullable=False),
    sa.Column('preferred_meeting_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('min_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('max_meetings_per_day', sa.Integer(), nullable=False),
    sa.Column('do_not_schedule_days', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('do_not_schedule_times', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('auto_reschedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('lunch_block_enabled', sa.Boolean(), nullable=False),
    sa.Column('lunch_start_hour', sa.Integer(), nullable=False),
    sa.Column('lunch_duration_hours', sa.Integer(), nullable=False),
    sa.Column('lunch_end_hour', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_preferences_tenant_id'), 'scheduling_preferences', ['tenant_id'], unique=False)
    op.create_table('store_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_notifications_tenant_id'), 'store_notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_store_notifications_user_id'), 'store_notifications', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.String(length=30), nullable=True),
    sa.Column('related_contact_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index('ix_tasks_tenant_status', 'tasks', ['tenant_id', 'status'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_number', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_tenant_id'), 'tickets', ['tenant_id'], unique=False)
    op.create_index('ix_tickets_tenant_status', 'tickets', ['tenant_id', 'status'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steps_executed', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('current_step_id', sa.String(length=50), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_tenant_id'), 'workflow_executions', ['tenant_id'], unique=False)
    op.create_index('ix_workflow_executions_tenant_status', 'workflow_executions', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_workflow_executions_tenant_workflow_id', 'workflow_executions', ['tenant_id', 'workflow_id'], unique=False)
    op.create_table('workflow_rules',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_rules_tenant_enabled', 'workflow_rules', ['tenant_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_workflow_rules_tenant_id'), 'workflow_rules', ['tenant_id'], unique=False)
    op.create_table('workforce_schedules',
    sa.Column('mission_id', sa.String(length=255), nullable=False),
    sa.Column('mission_name', sa.String(length=180), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=40), nullable=False),
    sa.Column('schedule_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('mission_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('next_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution_result', sa.String(length=40), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('pending_approval_count', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profiles.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workforce_schedules_tenant_enabled', 'workforce_schedules', ['tenant_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_workforce_schedules_tenant_id'), 'workforce_schedules', ['tenant_id'], unique=False)
    op.create_index('ix_workforce_schedules_tenant_next_execution', 'workforce_schedules', ['tenant_id', 'next_execution_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workforce_schedules_tenant_next_execution', table_name='workforce_schedules')
    op.drop_index(op.f('ix_workforce_schedules_tenant_id'), table_name='workforce_schedules')
    op.drop_index('ix_workforce_schedules_tenant_enabled', table_name='workforce_schedules')
    op.drop_table('workforce_schedules')
    op.drop_index(op.f('ix_workflow_rules_tenant_id'), table_name='workflow_rules')
    op.drop_index('ix_workflow_rules_tenant_enabled', table_name='workflow_rules')
    op.drop_table('workflow_rules')
    op.drop_index('ix_workflow_executions_tenant_workflow_id', table_name='workflow_executions')
    op.drop_index('ix_workflow_executions_tenant_status', table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_tenant_id'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('ix_tickets_tenant_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_tenant_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_tasks_tenant_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_store_notifications_user_id'), table_name='store_notifications')
    op.drop_index(op.f('ix_store_notifications_tenant_id'), table_name='store_notifications')
    op.drop_table('store_notifications')
    op.drop_index(op.f('ix_scheduling_preferences_tenant_id'), table_name='scheduling_preferences')
    op.drop_table('scheduling_preferences')
    op.drop_index('ix_scheduled_posts_tenant_platform', table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_tenant_id'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index('ix_mission_jobs_tenant_status', table_name='mission_jobs')
    op.drop_index('ix_mission_jobs_tenant_schedule_id', table_name='mission_jobs')
    op.drop_index(op.f('ix_mission_jobs_tenant_id'), table_name='mission_jobs')
    op.drop_table('mission_jobs')
    op.drop_index('ix_meetings_tenant_status', table_name='meetings')
    op.drop_index(op.f('ix_meetings_tenant_id'), table_name='meetings')
    op.drop_index('ix_meetings_tenant_datetime', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_meeting_templates_tenant_id'), table_name='meeting_templates')
    op.drop_table('meeting_templates')
    op.drop_index(op.f('ix_meeting_recaps_tenant_id'), table_name='meeting_recaps')
    op.drop_table('meeting_recaps')
    op.drop_index(op.f('ix_meeting_preps_tenant_id'), table_name='meeting_preps')
    op.drop_table('meeting_preps')
    op.drop_index(op.f('ix_meeting_consent_logs_tenant_id'), table_name='meeting_consent_logs')
    op.drop_table('meeting_consent_logs')
    op.drop_index('ix_leads_tenant_status', table_name='leads')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_job_executions_tenant_status', table_name='job_executions')
    op.drop_index(op.f('ix_job_executions_tenant_id'), table_name='job_executions')
    op.drop_index('ix_job_executions_job_id', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_inbox_messages_tenant_status', table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_tenant_id'), table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index('ix_emails_tenant_status', table_name='emails')
    op.drop_index('ix_emails_tenant_labels', table_name='emails')
    op.drop_index(op.f('ix_emails_tenant_id'), table_name='emails')
    op.drop_index('ix_emails_tenant_from', table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_email_templates_tenant_id'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_email_sequences_tenant_id'), table_name='email_sequences')
    op.drop_table('email_sequences')
    op.drop_index('ix_email_oauth_tenant_provider', table_name='email_oauth_credentials')
    op.drop_index(op.f('ix_email_oauth_credentials_tenant_id'), table_name='email_oauth_credentials')
    op.drop_table('email_oauth_credentials')
    op.drop_index('ix_email_drafts_tenant_status', table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_tenant_id'), table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index(op.f('ix_email_consent_logs_tenant_id'), table_name='email_consent_logs')
    op.drop_table('email_consent_logs')
    op.drop_index(op.f('ix_email_analytics_tenant_id'), table_name='email_analytics')
    op.drop_index('ix_email_analytics_tenant_date', table_name='email_analytics')
    op.drop_table('email_analytics')
    op.drop_index('ix_deals_tenant_stage', table_name='deals')
    op.drop_index(op.f('ix_deals_tenant_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index('ix_contacts_tenant_email', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_calendar_oauth_tenant_provider', table_name='calendar_oauth_credentials')
    op.drop_index(op.f('ix_calendar_oauth_credentials_tenant_id'), table_name='calendar_oauth_credentials')
    op.drop_table('calendar_oauth_credentials')
    op.drop_index('ix_calendar_events_tenant_provider', table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_tenant_id'), table_name='calendar_events')
    op.drop_index('ix_calendar_events_tenant_datetime', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_activities_tenant_type', table_name='activities')
    op.drop_index(op.f('ix_activities_tenant_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_contact_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('tenant_profiles')
    # ### end Alembic commands ###
