// AUTO-GENERATED by scripts/build-route-index.mjs — do not edit by hand.
// Regenerate with `npm run build:routes`.

export type RouteIndexEntry = {
  route: string;
  title: string;
  section: string;
  group: string;
  /** Alternate wording (mostly legacy nav labels) that should still match. */
  keywords: readonly string[];
  /** Internal engineering telemetry — excluded from customer search and nav. */
  internal?: boolean;
};

export const ROUTE_INDEX: readonly RouteIndexEntry[] = [
  {
    "route": "/account",
    "title": "Account Overview",
    "section": "settings",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/account/orders",
    "title": "Order Details",
    "section": "settings",
    "group": "Account",
    "keywords": []
  },
  {
    "route": "/account/profile",
    "title": "Personal Details",
    "section": "settings",
    "group": "Account",
    "keywords": []
  },
  {
    "route": "/account/settings",
    "title": "Settings",
    "section": "settings",
    "group": "Account",
    "keywords": []
  },
  {
    "route": "/account/wallet",
    "title": "Wallet For Credits",
    "section": "settings",
    "group": "Account",
    "keywords": []
  },
  {
    "route": "/ads-generation",
    "title": "AI Ads Generation",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/affiliate",
    "title": "Grow With Nuxtron As A Partner",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/affiliate/dashboard",
    "title": "Partner Performance",
    "section": "apps",
    "group": "Affiliate",
    "keywords": []
  },
  {
    "route": "/ai-analytics",
    "title": "AI Analytics",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/ai-search-impact-calculator",
    "title": "AI Search Impact Calculator",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/ai-security",
    "title": "AI Security Center",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/ai-visibility-dashboard",
    "title": "AI Crawler Visibility Dashboard",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/api-governance",
    "title": "API Governance And Third-Party Economics",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/benchmarks",
    "title": "Performance Benchmarks",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/billing",
    "title": "Billing Center",
    "section": "settings",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/billing/success",
    "title": "Activating your plan…",
    "section": "settings",
    "group": "Billing",
    "keywords": []
  },
  {
    "route": "/buffer-analyze",
    "title": "Analyze",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/buffer-collaborate",
    "title": "Collaborate",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/buffer-community",
    "title": "Community",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/buffer-create",
    "title": "Create",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/buffer-publish",
    "title": "Publish",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/buffer-startpage",
    "title": "Start Page",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/competitive-benchmarking",
    "title": "Competitive Benchmarking",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/content-generation",
    "title": "AI Content Generation",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/cost-saving-calculator",
    "title": "SEO Automation Cost Saving Calculator",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/crm",
    "title": "CRM Command Center",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/crm/abm",
    "title": "CRM ABM Command Center",
    "section": "apps",
    "group": "CRM",
    "keywords": []
  },
  {
    "route": "/dashboard",
    "title": "Dashboard",
    "section": "dashboard",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/disputes",
    "title": "Disputes Dashboard",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/finance-ops",
    "title": "Finance Ops",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/ira",
    "title": "IRA Control Center",
    "section": "ai",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/ira-monitor",
    "title": "IRA Monitor",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/media-processing",
    "title": "Sandboxed Media Processing",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/outcome-graph",
    "title": "Outcome Graph",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/platform",
    "title": "Nuxtron Unified Platform Surface",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/platform-ops",
    "title": "Platform Ops",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/platform/ai-agent",
    "title": "Kodee-Class AI Agent",
    "section": "apps",
    "group": "Platform",
    "keywords": []
  },
  {
    "route": "/platform/backend",
    "title": "Super Admin Backend",
    "section": "apps",
    "group": "Platform",
    "keywords": []
  },
  {
    "route": "/platform/owly-writer-ai",
    "title": "Owly Writer AI",
    "section": "apps",
    "group": "Platform",
    "keywords": []
  },
  {
    "route": "/playbooks",
    "title": "Integration Playbooks",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/reviews",
    "title": "Reviews and Reputation",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/seo",
    "title": "SEO Platform",
    "section": "seo",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/seo-aeo-geo-audit-tool",
    "title": "SEO AEO GEO Audit Tool",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/seo-analysis",
    "title": "AI SEO Analysis",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/seo/accessibility",
    "title": "Accessibility Optimizer",
    "section": "seo",
    "group": "Accessibility & Media",
    "keywords": []
  },
  {
    "route": "/seo/ads-calendar",
    "title": "Campaign Calendar",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/ads-campaigns",
    "title": "Campaign Manager",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/ads-connectors",
    "title": "Ad Network Connectors",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/ads-kpis",
    "title": "Ads KPI & Analytics",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/ads-metrics",
    "title": "Campaign Metrics",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/ads-smart-schedule",
    "title": "Smart Schedule &amp; Approval",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/aeo",
    "title": "AEO: Answer Engine Optimization",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/agency-platform",
    "title": "Agency & Multi-Tenant Platform",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/agent",
    "title": "Autonomous Agent Engine",
    "section": "seo",
    "group": "Experience Optimization",
    "keywords": []
  },
  {
    "route": "/seo/ahrefs-command-center",
    "title": "Ahrefs Command Center",
    "section": "seo",
    "group": "Ahrefs Core Tools",
    "keywords": [],
    "internal": true
  },
  {
    "route": "/seo/ai-creative-keyword-lab",
    "title": "AI Creative & Keyword Lab",
    "section": "seo",
    "group": "Ads Orchestration & Retail Media",
    "keywords": []
  },
  {
    "route": "/seo/aio",
    "title": "AIO-2",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/analytics",
    "title": "Traffic Analytics",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/attribution-conversion-intelligence",
    "title": "Attribution & Conversion Intelligence",
    "section": "seo",
    "group": "Ads Orchestration & Retail Media",
    "keywords": []
  },
  {
    "route": "/seo/backlink-intelligence",
    "title": "Backlink Intelligence Engine",
    "section": "seo",
    "group": "Core Foundations",
    "keywords": []
  },
  {
    "route": "/seo/botify-assist",
    "title": "Botify Assist Console",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/botify-automation",
    "title": "Botify Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/botify-integrations",
    "title": "Botify Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/botify-readiness",
    "title": "Botify Readiness Hub",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/brand-voice",
    "title": "Brand Voice & Style Engine",
    "section": "seo",
    "group": "Content & Distribution",
    "keywords": []
  },
  {
    "route": "/seo/brightedge-assist",
    "title": "BrightEdge Assist Console",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/brightedge-automation",
    "title": "BrightEdge Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/brightedge-integrations",
    "title": "BrightEdge Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/brightedge-readiness",
    "title": "BrightEdge Readiness Hub",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/budget-pacing-bid-engine",
    "title": "Budget Pacing & Bid Engine",
    "section": "seo",
    "group": "Ads Orchestration & Retail Media",
    "keywords": []
  },
  {
    "route": "/seo/client-portal",
    "title": "Client Portal",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/competitor",
    "title": "Competitor Intelligence Engine",
    "section": "seo",
    "group": "Schema & Optimization",
    "keywords": []
  },
  {
    "route": "/seo/content-auditor",
    "title": "Content Quality & Hallucination Auditor",
    "section": "seo",
    "group": "Monitoring & Observability",
    "keywords": []
  },
  {
    "route": "/seo/content-brief",
    "title": "Content Brief Generator",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/content-creation-blogging",
    "title": "Content Creation & Blogging Suite",
    "section": "seo",
    "group": "Core Foundations",
    "keywords": []
  },
  {
    "route": "/seo/contentshake",
    "title": "ContentShake AI",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/crawl-budget",
    "title": "Crawl Budget Optimizer",
    "section": "seo",
    "group": "Monitoring & Observability",
    "keywords": []
  },
  {
    "route": "/seo/cross-network-campaign-orchestrator",
    "title": "Cross-Network Campaign Orchestrator",
    "section": "seo",
    "group": "Ads Orchestration & Retail Media",
    "keywords": []
  },
  {
    "route": "/seo/cxao",
    "title": "CXAO: Conversational Experience Answer Optimization",
    "section": "seo",
    "group": "Experience Optimization",
    "keywords": []
  },
  {
    "route": "/seo/daeo",
    "title": "DAEO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/domain-overview",
    "title": "Domain Overview",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/ecommerce",
    "title": "eCommerce SEO Suite",
    "section": "seo",
    "group": "Experience Optimization",
    "keywords": []
  },
  {
    "route": "/seo/eeat",
    "title": "E-E-A-T Optimization Suite",
    "section": "seo",
    "group": "Experience Optimization",
    "keywords": []
  },
  {
    "route": "/seo/entity",
    "title": "Entity-First SEO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/eyeon",
    "title": "EyeOn Competitor Monitor",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/geo",
    "title": "GEO: Generative Engine Optimization",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/geoptie-assist",
    "title": "Geoptie Assist",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/geoptie-automation",
    "title": "Geoptie Automation",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/geoptie-integrations",
    "title": "Geoptie Integrations",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/geoptie-readiness",
    "title": "Geoptie Readiness",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/growth-playbooks",
    "title": "Growth Playbooks Automation",
    "section": "seo",
    "group": "Growth & Governance",
    "keywords": []
  },
  {
    "route": "/seo/gxo",
    "title": "GXO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/history",
    "title": "Analytics, Reporting & Intelligence",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/hootsuite-automation",
    "title": "Hootsuite Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": [],
    "internal": true
  },
  {
    "route": "/seo/hootsuite-integrations",
    "title": "Hootsuite Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/hootsuite-readiness",
    "title": "Hootsuite Readiness Hub",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": [],
    "internal": true
  },
  {
    "route": "/seo/integrations-automation",
    "title": "Integrations & Automation Layer",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/internal-linking",
    "title": "AI Internal Linking Engine",
    "section": "seo",
    "group": "Monitoring & Observability",
    "keywords": []
  },
  {
    "route": "/seo/international-multilingual",
    "title": "International & Multilingual SEO",
    "section": "seo",
    "group": "Expansion Modules",
    "keywords": []
  },
  {
    "route": "/seo/keywords",
    "title": "Keyword Research",
    "section": "seo",
    "group": "Core Foundations",
    "keywords": []
  },
  {
    "route": "/seo/knowledge-graph",
    "title": "Knowledge Graph Management",
    "section": "seo",
    "group": "Monitoring & Observability",
    "keywords": []
  },
  {
    "route": "/seo/landing",
    "title": "Landing Page Builder",
    "section": "seo",
    "group": "Accessibility & Media",
    "keywords": []
  },
  {
    "route": "/seo/linkbuilding",
    "title": "Autonomous Link Building",
    "section": "seo",
    "group": "Expansion Modules",
    "keywords": []
  },
  {
    "route": "/seo/llmo",
    "title": "LLMO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/local",
    "title": "Local SEO Optimizer",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/local-heatmap",
    "title": "Local Heatmap",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/local-seo",
    "title": "Local SEO Suite",
    "section": "seo",
    "group": "Expansion Modules",
    "keywords": []
  },
  {
    "route": "/seo/log-file",
    "title": "Log File Analysis Engine",
    "section": "seo",
    "group": "Content & Distribution",
    "keywords": []
  },
  {
    "route": "/seo/map-rank-tracker",
    "title": "Map Rank Tracker",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/market-explorer",
    "title": "Market Explorer",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/media",
    "title": "Image & Media SEO Engine",
    "section": "seo",
    "group": "Accessibility & Media",
    "keywords": []
  },
  {
    "route": "/seo/msvo",
    "title": "MSVO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/multi-channel-activation",
    "title": "Multi-Channel Activation Loop",
    "section": "seo",
    "group": "Growth & Governance",
    "keywords": []
  },
  {
    "route": "/seo/neo4j-automation",
    "title": "Neo4j Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/neo4j-integrations",
    "title": "Neo4j Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/news-discover",
    "title": "News SEO & Google Discover",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/on-page",
    "title": "On-Page Optimizer",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/one2target",
    "title": "One2Target",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/peao",
    "title": "PEAO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/performance",
    "title": "GTmetrix-Style Performance Audit",
    "section": "seo",
    "group": "Performance & Audits",
    "keywords": []
  },
  {
    "route": "/seo/pla-research",
    "title": "PLA Research",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/planner",
    "title": "SEO Execution Planner",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/platform-intelligence",
    "title": "Platform Matrix Score",
    "section": "seo",
    "group": "Performance & Audits",
    "keywords": []
  },
  {
    "route": "/seo/programmatic",
    "title": "Programmatic SEO Engine",
    "section": "seo",
    "group": "Experience Optimization",
    "keywords": []
  },
  {
    "route": "/seo/promptwatch-assist",
    "title": "Promptwatch Assist Console",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/promptwatch-automation",
    "title": "Promptwatch Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/promptwatch-integrations",
    "title": "Promptwatch Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/promptwatch-readiness",
    "title": "Promptwatch Readiness Hub",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/rag-search",
    "title": "RAG Site Search Engine",
    "section": "seo",
    "group": "Schema & Optimization",
    "keywords": []
  },
  {
    "route": "/seo/rank-tracking",
    "title": "Advanced Rank Tracking",
    "section": "seo",
    "group": "Core Foundations",
    "keywords": []
  },
  {
    "route": "/seo/realtime-monitoring",
    "title": "Real-Time Search & AI Monitoring",
    "section": "seo",
    "group": "Monitoring & Observability",
    "keywords": []
  },
  {
    "route": "/seo/retail-media-app-growth-hub",
    "title": "Retail Media & App Growth Hub",
    "section": "seo",
    "group": "Ads Orchestration & Retail Media",
    "keywords": []
  },
  {
    "route": "/seo/revenue-attribution",
    "title": "Revenue Attribution Intelligence",
    "section": "seo",
    "group": "Growth & Governance",
    "keywords": []
  },
  {
    "route": "/seo/reviews",
    "title": "Review & Reputation Engine",
    "section": "seo",
    "group": "Content & Distribution",
    "keywords": []
  },
  {
    "route": "/seo/sageo",
    "title": "SAGEO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/schemas",
    "title": "AI Schema Engine",
    "section": "seo",
    "group": "Schema & Optimization",
    "keywords": []
  },
  {
    "route": "/seo/security",
    "title": "Security & SEO Health Monitor",
    "section": "seo",
    "group": "Accessibility & Media",
    "keywords": []
  },
  {
    "route": "/seo/semrush-command-center",
    "title": "Semrush End-to-End SEO Operations",
    "section": "seo",
    "group": "SEO",
    "keywords": [],
    "internal": true
  },
  {
    "route": "/seo/seo-ab-testing",
    "title": "SEO A/B Testing Framework",
    "section": "seo",
    "group": "Experience Optimization",
    "keywords": []
  },
  {
    "route": "/seo/seo-ai",
    "title": "SEO-AI",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/seo-ai-assist",
    "title": "SEO.AI Assist Console",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/seo-ai-automation",
    "title": "SEO.AI Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/seo-ai-integrations",
    "title": "SEO.AI Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/seo-ai-readiness",
    "title": "SEO.AI Readiness Hub",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/site-migration",
    "title": "Site Migration SEO Manager",
    "section": "seo",
    "group": "Expansion Modules",
    "keywords": []
  },
  {
    "route": "/seo/social",
    "title": "Social SEO & Distribution",
    "section": "seo",
    "group": "Accessibility & Media",
    "keywords": []
  },
  {
    "route": "/seo/sproutsocial-automation",
    "title": "Sprout Social Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/surfer-automation",
    "title": "Surfer Automation",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/surfer-command-center",
    "title": "Surfer Command Center",
    "section": "seo",
    "group": "Surfer Core Tools",
    "keywords": [],
    "internal": true
  },
  {
    "route": "/seo/surfer-readiness",
    "title": "Surfer Readiness",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/surfer-setup-playbook",
    "title": "Surfer Setup Playbook",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/surfer-wiring-plan",
    "title": "Surfer Wiring Plan",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/sxo",
    "title": "SXO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/technical",
    "title": "AI Technical SEO Engine",
    "section": "seo",
    "group": "Monitoring & Observability",
    "keywords": []
  },
  {
    "route": "/seo/topical-map",
    "title": "Topical Map & Silo Builder",
    "section": "seo",
    "group": "Content & Distribution",
    "keywords": []
  },
  {
    "route": "/seo/trust-risk-governance",
    "title": "Trust & Risk Governance",
    "section": "seo",
    "group": "Growth & Governance",
    "keywords": []
  },
  {
    "route": "/seo/unified-ads-control-tower",
    "title": "Unified Ads Control Tower",
    "section": "seo",
    "group": "Ads Orchestration & Retail Media",
    "keywords": []
  },
  {
    "route": "/seo/ux",
    "title": "UX & Conversion Optimizer",
    "section": "seo",
    "group": "Schema & Optimization",
    "keywords": []
  },
  {
    "route": "/seo/video",
    "title": "Video SEO Module",
    "section": "seo",
    "group": "Expansion Modules",
    "keywords": []
  },
  {
    "route": "/seo/vso",
    "title": "VSO",
    "section": "seo",
    "group": "Search Intelligence",
    "keywords": []
  },
  {
    "route": "/seo/writer",
    "title": "AI Article Writer",
    "section": "seo",
    "group": "SEO",
    "keywords": []
  },
  {
    "route": "/seo/writesonic-assist",
    "title": "Writesonic Assist Console",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/writesonic-automation",
    "title": "Writesonic Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": [],
    "internal": true
  },
  {
    "route": "/seo/writesonic-integrations",
    "title": "Writesonic Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/writesonic-readiness",
    "title": "Writesonic Readiness Hub",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/yext-assist",
    "title": "Yext Assist Console",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/yext-automation",
    "title": "Yext Automation",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/yext-integrations",
    "title": "Yext Integrations",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/seo/yext-readiness",
    "title": "Yext Readiness Hub",
    "section": "seo",
    "group": "SaaS Platform",
    "keywords": []
  },
  {
    "route": "/siem",
    "title": "SIEM & Security Operations",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/smart-inbox",
    "title": "Smart Inbox",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/social-listening",
    "title": "Social Listening",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/social-media-roi",
    "title": "Social Media ROI",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/social-scheduling",
    "title": "Social Scheduling",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/studio",
    "title": "Studio",
    "section": "studio",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/studio/ads-engine",
    "title": "Creative Testing & Budget Optimization",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/agent-analytics",
    "title": "Agent Analytics",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/analytics",
    "title": "Live KPI & Platform Dashboards",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/answer-engine",
    "title": "Answer Engine Hub",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/avatar-builder",
    "title": "Avatar Builder",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/backlink-intelligence",
    "title": "Backlink Intelligence",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/brand-kit",
    "title": "Brand Kit",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/brands",
    "title": "Brand Hub",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/cdn-analytics",
    "title": "CDN Analytics",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/editor",
    "title": "Editor",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/faceless-video-engine",
    "title": "Faceless Video Engine",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/growth-suite",
    "title": "AI Growth Suite",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/image-direction",
    "title": "Image Direction",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/image-studio",
    "title": "AI Image Studio",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/intelligence",
    "title": "Intelligence",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/lately",
    "title": "Lately AI",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/lately/ab-testing",
    "title": "A/B Testing Engine",
    "section": "studio",
    "group": "Lately",
    "keywords": []
  },
  {
    "route": "/studio/lately/brand-hierarchy",
    "title": "Parent-Child Brand Hierarchy",
    "section": "studio",
    "group": "Lately",
    "keywords": []
  },
  {
    "route": "/studio/lately/brand-voice",
    "title": "Brand Voice DNA",
    "section": "studio",
    "group": "Lately",
    "keywords": []
  },
  {
    "route": "/studio/lately/repurpose",
    "title": "Longform Content Repurposer",
    "section": "studio",
    "group": "Lately",
    "keywords": []
  },
  {
    "route": "/studio/lately/roi-forecast",
    "title": "ROI Forecaster",
    "section": "studio",
    "group": "Lately",
    "keywords": []
  },
  {
    "route": "/studio/lately/word-cloud",
    "title": "Keyword Intelligence",
    "section": "studio",
    "group": "Lately",
    "keywords": []
  },
  {
    "route": "/studio/multilingual-ads",
    "title": "Multilingual Ads",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/prompt-volumes",
    "title": "Prompt Volumes",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/rank-tracker",
    "title": "Rank Tracker",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/reels-factory",
    "title": "Reels Factory",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/scheduler",
    "title": "Cross-Platform Content Scheduling",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/seo-suite",
    "title": "Topic Clustering & On-Page Optimization",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/short-video-factory",
    "title": "Short Video Factory",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio",
    "title": "Unified Social Studio Frontier Stack",
    "section": "social",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/accounts",
    "title": "Social Media Accounts",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/ads",
    "title": "Paid Social Advertising",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/advocacy",
    "title": "Employee Advocacy",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/analytics",
    "title": "Analytics & KPIs",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/approvals",
    "title": "Content Approvals",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/automation",
    "title": "Automation Engine",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/best-time",
    "title": "Best Time to Post",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/browser-capture",
    "title": "Browser Capture Pipeline",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/bulk-schedule",
    "title": "Bulk Scheduler",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/calendar",
    "title": "Campaign Calendar",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/inbox",
    "title": "Smart Inbox",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/influencers",
    "title": "Influencer CRM",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/link-in-bio",
    "title": "Link In Bio Commerce",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/listening",
    "title": "Social Listening",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/manychat",
    "title": "Manychat Automation Workspace",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/mobile",
    "title": "Mobile + PWA Ops",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/optimization",
    "title": "AI Optimization",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/posts",
    "title": "Social Posts",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/reports",
    "title": "Report Builder",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/reviews",
    "title": "Review Management",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/streams",
    "title": "Monitoring Streams",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/trends",
    "title": "Social Trends & Intelligence",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/social-studio/ugc",
    "title": "UGC Management",
    "section": "social",
    "group": "Social Studio",
    "keywords": []
  },
  {
    "route": "/studio/team",
    "title": "Roles, Approvals & Workspace Controls",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/template-system",
    "title": "Template System",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/workflow-orchestrator",
    "title": "Workflow Orchestrator",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/studio/workspace",
    "title": "Workspace",
    "section": "studio",
    "group": "Studio",
    "keywords": []
  },
  {
    "route": "/trust-center",
    "title": "Trust Center",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/vendor-inventory-report",
    "title": "Unified Third-Party Vendor Report",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/vse",
    "title": "⚡ Viral Singularity Engine",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/white-label",
    "title": "White Label",
    "section": "apps",
    "group": "General",
    "keywords": []
  },
  {
    "route": "/workflows",
    "title": "Workflows Automation",
    "section": "apps",
    "group": "General",
    "keywords": []
  }
];

/** Routes that only re-export or redirect to a canonical page. */
export const ROUTE_ALIASES: Readonly<Record<string, string>> = {
  "/airanklab/wiring": "/seo/integrations-automation",
  "/hubspot-e2e": "/crm",
  "/seo/ai-content-grader": "../content-auditor/page",
  "/seo/ai-content-helper": "../content-creation-blogging/page",
  "/seo/ai-localization": "@/app/(public)/tools/translation-studio/page",
  "/seo/bot-analytics": "/seo/realtime-monitoring",
  "/seo/brand-radar": "/seo/realtime-monitoring",
  "/seo/content-explorer": "/seo/content-creation-blogging",
  "/seo/custom-prompts": "/seo/planner",
  "/seo/dashboard": "/dashboard",
  "/seo/gbp-monitor": "/seo/map-rank-tracker",
  "/seo/gsc-insights": "/seo/history",
  "/seo/keywords-explorer": "/seo/planner",
  "/seo/neo4j-readiness": "/seo/neo4j-integrations",
  "/seo/nsvo": "../msvo/page",
  "/seo/patches": "../technical/page",
  "/seo/portfolios": "/seo/agency-platform",
  "/seo/rank-tracker": "/seo/rank-tracking",
  "/seo/report-builder": "/seo/client-portal",
  "/seo/site-audit": "/seo/technical",
  "/seo/site-explorer": "/seo/domain-overview",
  "/seo/social-media-manager": "/studio/social-studio",
  "/seo/web-analytics": "/seo/history",
  "/studio/ar-experience-studio": "../social-studio/page",
  "/studio/blog-studio": "../social-studio/page",
  "/studio/editing-suite": "../social-studio/page",
  "/studio/hologram-stage": "../social-studio/page",
  "/studio/image-slider": "../social-studio/page",
  "/studio/keyword-research": "../rank-tracker/page",
  "/studio/music-generator": "../social-studio/page",
  "/studio/social-accounts": "../social-studio/accounts/page",
  "/studio/social-ads": "../social-studio/ads/page",
  "/studio/social-advocacy": "../social-studio/advocacy/page",
  "/studio/social-analytics": "../social-studio/analytics/page",
  "/studio/social-approvals": "../social-studio/approvals/page",
  "/studio/social-automation": "../social-studio/automation/page",
  "/studio/social-best-time": "../social-studio/best-time/page",
  "/studio/social-bulk-schedule": "../social-studio/bulk-schedule/page",
  "/studio/social-calendar": "../social-studio/calendar/page",
  "/studio/social-inbox": "../social-studio/inbox/page",
  "/studio/social-influencers": "../social-studio/influencers/page",
  "/studio/social-link-in-bio": "../social-studio/link-in-bio/page",
  "/studio/social-listening": "../social-studio/listening/page",
  "/studio/social-posts": "../social-studio/posts/page",
  "/studio/social-reports": "../social-studio/reports/page",
  "/studio/social-reviews": "../social-studio/reviews/page",
  "/studio/social-streams": "../social-studio/streams/page",
  "/studio/social-trends": "../social-studio/trends/page",
  "/studio/social-ugc": "../social-studio/ugc/page",
  "/studio/sound-design": "../social-studio/page",
  "/studio/vr-world-builder": "../social-studio/page"
};
