export type ModuleTier = 'Core' | 'AI' | 'New' | 'Experiment' | 'SaaS' | 'Parity';

export type ModuleCatalogEntry = {
  title: string;
  tier?: ModuleTier;
  summary: string;
  category: string;
  routePath: string;
  moduleKey?: string;
};

export const SEO_MODULE_CATALOG: ModuleCatalogEntry[] = [
  {
    title: 'SEO-AI',
    tier: 'Core',
    summary: 'AI-enhanced traditional SEO workflows spanning keyword research, content, and technical signals.',
    category: 'Search Intelligence',
    routePath: '/seo/seo-ai',
    moduleKey: 'seo-ai',
  },
  {
    title: 'Keyword Research',
    tier: 'Core',
    summary: 'Intent, clustering, SERP features, and keyword opportunity scoring.',
    category: 'Core Foundations',
    routePath: '/seo/keywords',
    moduleKey: 'keyword-research-engine',
  },
  {
    title: 'AEO: Answer Engine Optimization',
    tier: 'Core',
    summary: 'OpenLens + Playwright + LlamaIndex + JSON-LD optimization for answer engines.',
    category: 'Search Intelligence',
    routePath: '/seo/aeo',
    moduleKey: 'aeo',
  },
  {
    title: 'GEO: Generative Engine Optimization',
    tier: 'Core',
    summary: 'Llama-3 + RAG over SERPs, AI answers, and site content for generative overviews.',
    category: 'Search Intelligence',
    routePath: '/seo/geo',
    moduleKey: 'geo',
  },
  {
    title: 'AIO-2',
    tier: 'New',
    summary: 'Agentic intelligence optimization for content and search workflows.',
    category: 'Search Intelligence',
    routePath: '/seo/aio',
    moduleKey: 'aio',
  },
  {
    title: 'LLMO',
    tier: 'New',
    summary: 'LLM optimization for brand accuracy, retrieval, and answer quality.',
    category: 'Search Intelligence',
    routePath: '/seo/llmo',
    moduleKey: 'llmo',
  },
  {
    title: 'SAGEO',
    summary: 'Search-augmented generative SEO planning and synthesis.',
    category: 'Search Intelligence',
    routePath: '/seo/sageo',
    moduleKey: 'sageo',
  },
  {
    title: 'VSO',
    summary: 'Voice search optimization for question-answer and assistant-driven queries.',
    category: 'Search Intelligence',
    routePath: '/seo/vso',
    moduleKey: 'vso',
  },
  {
    title: 'SXO',
    summary: 'Search experience optimization spanning UX, engagement, and SERP behavior.',
    category: 'Search Intelligence',
    routePath: '/seo/sxo',
    moduleKey: 'sxo',
  },
  {
    title: 'GXO',
    tier: 'New',
    summary: 'Google AI Overview and generative experience optimization.',
    category: 'Search Intelligence',
    routePath: '/seo/gxo',
    moduleKey: 'gxo',
  },
  {
    title: 'Entity-First SEO',
    summary: 'Knowledge graph and entity-driven optimization workflows.',
    category: 'Search Intelligence',
    routePath: '/seo/entity',
    moduleKey: 'entity',
  },
  {
    title: 'PEAO',
    summary: 'Predictive engine algorithm optimization using trend and anomaly forecasting.',
    category: 'Search Intelligence',
    routePath: '/seo/peao',
    moduleKey: 'peao',
  },
  {
    title: 'MSVO',
    summary: 'Multi-surface visibility optimization across search, AI, and owned channels.',
    category: 'Search Intelligence',
    routePath: '/seo/msvo',
    moduleKey: 'msvo',
  },
  {
    title: 'NSVO (MSVO Alias)',
    summary: 'Compatibility alias for multi-surface visibility optimization naming.',
    category: 'Search Intelligence',
    routePath: '/seo/nsvo',
    moduleKey: 'nsvo',
  },
  {
    title: 'DAEO',
    summary: 'Decentralized answer engine optimization for self-hosted and federated search.',
    category: 'Search Intelligence',
    routePath: '/seo/daeo',
    moduleKey: 'daeo',
  },

  {
    title: 'CXAO: Conversational Experience Answer Optimization',
    tier: 'AI',
    summary: 'Llama-3 + RAG + Next.js chat flows + PostHog optimization for conversational outcomes.',
    category: 'Experience Optimization',
    routePath: '/seo/cxao',
    moduleKey: 'cxao',
  },
  {
    title: 'E-E-A-T Optimization Suite',
    summary: 'Authority, trust, expertise, and provenance scoring.',
    category: 'Experience Optimization',
    routePath: '/seo/eeat',
    moduleKey: 'eeat',
  },
  {
    title: 'Autonomous Agent Engine',
    tier: 'AI',
    summary: 'Plan, execute, and evaluate SEO workflows with agentic loops.',
    category: 'Experience Optimization',
    routePath: '/seo/agent',
    moduleKey: 'agent',
  },
  {
    title: 'Programmatic SEO Engine',
    summary: 'Programmatic landing page and template-driven SEO at scale.',
    category: 'Experience Optimization',
    routePath: '/seo/programmatic',
    moduleKey: 'programmatic-seo-engine',
  },
  {
    title: 'SEO A/B Testing Framework',
    tier: 'Experiment',
    summary: 'Next.js variants + feature flags + PostHog experiments + Llama-3 analysis.',
    category: 'Experience Optimization',
    routePath: '/seo/seo-ab-testing',
    moduleKey: 'seo-ab-testing-framework',
  },
  {
    title: 'eCommerce SEO Suite',
    summary: 'Product, category, and merchandising-focused SEO workflows.',
    category: 'Experience Optimization',
    routePath: '/seo/ecommerce',
    moduleKey: 'ecommerce-seo-suite',
  },

  {
    title: 'Revenue Attribution Intelligence',
    summary: 'Attribution from search and AI channels through to revenue outcomes.',
    category: 'Growth & Governance',
    routePath: '/seo/revenue-attribution',
    moduleKey: 'revenue-attribution-intelligence',
  },
  {
    title: 'Growth Playbooks Automation',
    summary: 'Automated growth playbook execution and measurement.',
    category: 'Growth & Governance',
    routePath: '/seo/growth-playbooks',
    moduleKey: 'growth-playbooks-automation',
  },
  {
    title: 'Trust & Risk Governance',
    summary: 'Policy, governance, and risk controls for SEO and AI execution.',
    category: 'Growth & Governance',
    routePath: '/seo/trust-risk-governance',
    moduleKey: 'trust-risk-governance',
  },
  {
    title: 'Multi-Channel Activation Loop',
    summary: 'Activation and distribution across search, social, and lifecycle channels.',
    category: 'Growth & Governance',
    routePath: '/seo/multi-channel-activation',
    moduleKey: 'multi-channel-activation-loop',
  },

  {
    title: 'Autonomous Link Building',
    summary: 'Backlink discovery, prospecting, and workflow orchestration.',
    category: 'Expansion Modules',
    routePath: '/seo/linkbuilding',
    moduleKey: 'autonomous-link-building',
  },
  {
    title: 'International & Multilingual SEO',
    summary: 'Regionalization, hreflang, and multilingual search optimization.',
    category: 'Expansion Modules',
    routePath: '/seo/international-multilingual',
    moduleKey: 'international-multilingual-seo',
  },
  {
    title: 'Site Migration SEO Manager',
    summary: 'SEO-safe migration planning, validation, and monitoring.',
    category: 'Expansion Modules',
    routePath: '/seo/site-migration',
    moduleKey: 'site-migration-seo-manager',
  },
  {
    title: 'Video SEO Module',
    summary: 'Video metadata, transcript, and discovery optimization.',
    category: 'Expansion Modules',
    routePath: '/seo/video',
    moduleKey: 'video-seo-module',
  },
  {
    title: 'Local SEO Suite',
    summary: 'Local intent, map visibility, location pages, and review signals.',
    category: 'Expansion Modules',
    routePath: '/seo/local-seo',
    moduleKey: 'local-seo-suite',
  },

  {
    title: 'Backlink Intelligence Engine',
    tier: 'Core',
    summary: 'Advanced link graph analysis with Neo4j-ready topology and topical clustering.',
    category: 'Core Foundations',
    routePath: '/seo/backlink-intelligence',
    moduleKey: 'backlink-intelligence-engine',
  },
  {
    title: 'Advanced Rank Tracking',
    tier: 'Core',
    summary: 'Time-series ranking data, volatility detection, competitor tracking, and SERP forecasting.',
    category: 'Core Foundations',
    routePath: '/seo/rank-tracking',
    moduleKey: 'advanced-rank-tracking',
  },
  {
    title: 'Content Creation & Blogging Suite',
    tier: 'Core',
    summary: 'AI-powered blogging strategy, content calendar, SEO briefs, and multimedia planning.',
    category: 'Core Foundations',
    routePath: '/seo/content-creation-blogging',
    moduleKey: 'content-creation-blogging-suite',
  },

  {
    title: 'News SEO & Google Discover',
    summary: 'Freshness, Top Stories, and Discover optimization.',
    category: 'SaaS Platform',
    routePath: '/seo/news-discover',
    moduleKey: 'news-seo-google-discover',
  },
  {
    title: 'Analytics, Reporting & Intelligence',
    summary: 'Central analytics and reporting across the SEO estate.',
    category: 'SaaS Platform',
    routePath: '/seo/history',
    moduleKey: 'analytics-reporting-intelligence',
  },
  {
    title: 'Agency & Multi-Tenant Platform',
    summary: 'Tenant-aware SEO operations, workspaces, and governance.',
    category: 'SaaS Platform',
    routePath: '/seo/agency-platform',
    moduleKey: 'agency-multi-tenant-platform',
  },
  {
    title: 'Integrations & Automation Layer',
    summary: 'Third-party integrations, connectors, and automation plumbing.',
    category: 'SaaS Platform',
    routePath: '/seo/integrations-automation',
    moduleKey: 'integrations-automation-layer',
  },

  {
    title: 'Unified Ads Control Tower',
    tier: 'Core',
    summary:
      'Production-grade command center for orchestrating Google, Microsoft, Amazon, Apple Search Ads, and YouTube campaigns from one operating plane.',
    category: 'Ads Orchestration & Retail Media',
    routePath: '/seo/unified-ads-control-tower',
    moduleKey: 'unified-ads-control-tower',
  },
  {
    title: 'Cross-Network Campaign Orchestrator',
    tier: 'AI',
    summary:
      'Advanced workflow engine for cloning, localizing, and synchronizing campaigns, ad groups, audiences, and creative packages across major ad networks.',
    category: 'Ads Orchestration & Retail Media',
    routePath: '/seo/cross-network-campaign-orchestrator',
    moduleKey: 'cross-network-campaign-orchestrator',
  },
  {
    title: 'Budget Pacing & Bid Engine',
    tier: 'AI',
    summary:
      'Rule-driven and model-assisted bid engine that monitors CTR, CPA, CPC, ROAS, and spend pacing to keep campaigns on target throughout the day.',
    category: 'Ads Orchestration & Retail Media',
    routePath: '/seo/budget-pacing-bid-engine',
    moduleKey: 'budget-pacing-bid-engine',
  },
  {
    title: 'Attribution & Conversion Intelligence',
    tier: 'Core',
    summary:
      'Server-side tracking and attribution fabric that unifies ad clicks, conversions, revenue events, and offline outcomes into decision-grade reporting.',
    category: 'Ads Orchestration & Retail Media',
    routePath: '/seo/attribution-conversion-intelligence',
    moduleKey: 'attribution-conversion-intelligence',
  },
  {
    title: 'AI Creative & Keyword Lab',
    tier: 'AI',
    summary:
      'Advanced AI workspace for generating ad copy, keyword clusters, negative keywords, landing-page angles, and channel-specific test matrices.',
    category: 'Ads Orchestration & Retail Media',
    routePath: '/seo/ai-creative-keyword-lab',
    moduleKey: 'ai-creative-keyword-lab',
  },
  {
    title: 'Retail Media & App Growth Hub',
    tier: 'New',
    summary:
      'Specialized command module for Amazon retail media, Apple Search Ads, app growth measurement, and marketplace-specific merchandising loops.',
    category: 'Ads Orchestration & Retail Media',
    routePath: '/seo/retail-media-app-growth-hub',
    moduleKey: 'retail-media-app-growth-hub',
  },

  {
    title: 'Real-Time Search & AI Monitoring',
    summary: 'Realtime engine volatility, visibility tracking, and alerting.',
    category: 'Monitoring & Observability',
    routePath: '/seo/realtime-monitoring',
    moduleKey: 'real-time-search-ai-monitoring',
  },
  {
    title: 'AI Technical SEO Engine',
    summary: 'Autonomous technical SEO diagnosis and remediation.',
    category: 'Monitoring & Observability',
    routePath: '/seo/technical',
    moduleKey: 'ai-technical-seo-engine',
  },
  {
    title: 'Content Quality & Hallucination Auditor',
    summary: 'Factuality, citation, and answer-quality auditing for AI-assisted content.',
    category: 'Monitoring & Observability',
    routePath: '/seo/content-auditor',
    moduleKey: 'content-quality-hallucination-auditor',
  },
  {
    title: 'Knowledge Graph Management',
    summary: 'Entity graph construction, enrichment, and validation.',
    category: 'Monitoring & Observability',
    routePath: '/seo/knowledge-graph',
    moduleKey: 'knowledge-graph-management',
  },
  {
    title: 'AI Internal Linking Engine',
    summary: 'Semantic link opportunity detection and internal authority flow design.',
    category: 'Monitoring & Observability',
    routePath: '/seo/internal-linking',
    moduleKey: 'ai-internal-linking-engine',
  },
  {
    title: 'Crawl Budget Optimizer',
    summary: 'Log-based crawl efficiency and priority optimization.',
    category: 'Monitoring & Observability',
    routePath: '/seo/crawl-budget',
    moduleKey: 'crawl-budget-optimizer',
  },

  {
    title: 'AI Schema Engine',
    summary: 'Automated schema generation, validation, and enhancement.',
    category: 'Schema & Optimization',
    routePath: '/seo/schemas',
    moduleKey: 'ai-schema-engine',
  },
  {
    title: 'UX & Conversion Optimizer',
    summary: 'Behavior, conversion, and UX optimization from search traffic.',
    category: 'Schema & Optimization',
    routePath: '/seo/ux',
    moduleKey: 'ux-conversion-optimizer',
  },
  {
    title: 'RAG Site Search Engine',
    summary: 'Semantic site search powered by retrieval and reasoning.',
    category: 'Schema & Optimization',
    routePath: '/seo/rag-search',
    moduleKey: 'rag-site-search-engine',
  },
  {
    title: 'Competitor Intelligence Engine',
    summary: 'Competitive search, AI visibility, and content gap intelligence.',
    category: 'Schema & Optimization',
    routePath: '/seo/competitor',
    moduleKey: 'competitor-intelligence-engine',
  },

  {
    title: 'Topical Map & Silo Builder',
    summary: 'Topic clustering, hub-spoke architecture, and editorial map generation.',
    category: 'Content & Distribution',
    routePath: '/seo/topical-map',
    moduleKey: 'topical-map-silo-builder',
  },
  {
    title: 'Log File Analysis Engine',
    summary: 'Crawl-log ingestion, anomaly detection, and bot behavior analysis.',
    category: 'Content & Distribution',
    routePath: '/seo/log-file',
    moduleKey: 'log-file-analysis-engine',
  },
  {
    title: 'Review & Reputation Engine',
    summary: 'Review mining, sentiment analysis, and reputation response workflows.',
    category: 'Content & Distribution',
    routePath: '/seo/reviews',
    moduleKey: 'review-reputation-engine',
  },
  {
    title: 'Brand Voice & Style Engine',
    summary: 'Brand-consistent rewriting and tone governance for SEO content.',
    category: 'Content & Distribution',
    routePath: '/seo/brand-voice',
    moduleKey: 'brand-voice-style-engine',
  },

  {
    title: 'Accessibility Optimizer',
    summary: 'WCAG, readability, and assistive discoverability optimization.',
    category: 'Accessibility & Media',
    routePath: '/seo/accessibility',
    moduleKey: 'accessibility-optimizer',
  },
  {
    title: 'Image & Media SEO Engine',
    summary: 'Alt text, metadata, compression, and media search optimization.',
    category: 'Accessibility & Media',
    routePath: '/seo/media',
    moduleKey: 'image-media-seo-engine',
  },
  {
    title: 'Social SEO & Distribution',
    summary: 'Search-aware social distribution and multi-surface promotion.',
    category: 'Accessibility & Media',
    routePath: '/seo/social',
    moduleKey: 'social-seo-distribution',
  },
  {
    title: 'Landing Page Builder',
    summary: 'Conversion-ready landing pages with schema and experimentation hooks.',
    category: 'Accessibility & Media',
    routePath: '/seo/landing',
    moduleKey: 'landing-page-builder',
  },
  {
    title: 'Security & SEO Health Monitor',
    summary: 'Security posture, spam, cloaking, and SEO integrity monitoring.',
    category: 'Accessibility & Media',
    routePath: '/seo/security',
    moduleKey: 'security-seo-health-monitor',
  },

  {
    title: 'GTmetrix-Style Performance Audit',
    tier: 'New',
    summary: 'Lighthouse, CDP waterfall, Web Vitals, filmstrip, history, and alert-driven performance auditing.',
    category: 'Performance & Audits',
    routePath: '/seo/performance',
    moduleKey: 'gtmetrix-style-performance-audit',
  },
  {
    title: 'Platform Matrix Score',
    tier: 'Core',
    summary:
      'Cross-module health score, SLA compliance, latency matrix, AI governance, anomaly detection, and ranked action items.',
    category: 'Performance & Audits',
    routePath: '/seo/platform-intelligence',
    moduleKey: 'platform-matrix-score',
  },

  {
    title: 'Botify Readiness Hub',
    tier: 'Core',
    summary: 'Operational readiness center for Botify parity, gate outcomes, and integration coverage.',
    category: 'SaaS Platform',
    routePath: '/seo/botify-readiness',
    moduleKey: 'botify-readiness-hub',
  },
  {
    title: 'Botify Automation',
    tier: 'Core',
    summary: 'Project and run orchestration layer for end-to-end Botify automation workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/botify-automation',
    moduleKey: 'botify-automation',
  },
  {
    title: 'Botify Integrations',
    tier: 'AI',
    summary: 'Provider checklist, preflight diagnostics, and remediation exports for Botify integrations.',
    category: 'SaaS Platform',
    routePath: '/seo/botify-integrations',
    moduleKey: 'botify-integrations',
  },
  {
    title: 'Botify Assist Console',
    tier: 'AI',
    summary: 'Prompt-based operations console for Botify Assist with workflow handoff guidance.',
    category: 'SaaS Platform',
    routePath: '/seo/botify-assist',
    moduleKey: 'botify-assist-console',
  },
  {
    title: 'Hootsuite Readiness Hub',
    tier: 'Core',
    summary: 'Readiness and production gate center for the Hootsuite automation slice.',
    category: 'SaaS Platform',
    routePath: '/seo/hootsuite-readiness',
    moduleKey: 'hootsuite-readiness-hub',
  },
  {
    title: 'Hootsuite Automation',
    tier: 'Core',
    summary: 'Project, run, and schedule orchestration for Hootsuite workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/hootsuite-automation',
    moduleKey: 'hootsuite-automation',
  },
  {
    title: 'Hootsuite Integrations',
    tier: 'AI',
    summary: 'Provider checklist, preflight diagnostics, and remediation exports for Hootsuite integrations.',
    category: 'SaaS Platform',
    routePath: '/seo/hootsuite-integrations',
    moduleKey: 'hootsuite-integrations',
  },
  {
    title: 'Sprout Social Automation',
    tier: 'Core',
    summary: 'End-to-end production console for Sprout-style social publishing, inbox, listening, and automation.',
    category: 'SaaS Platform',
    routePath: '/seo/sproutsocial-automation',
    moduleKey: 'sproutsocial-automation',
  },
  {
    title: 'Yext Readiness Hub',
    tier: 'Core',
    summary: 'Readiness and production gate center for the Yext automation slice.',
    category: 'SaaS Platform',
    routePath: '/seo/yext-readiness',
    moduleKey: 'yext-readiness-hub',
  },
  {
    title: 'Yext Automation',
    tier: 'Core',
    summary: 'Project, run, schedule, and product orchestration for Yext workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/yext-automation',
    moduleKey: 'yext-automation',
  },
  {
    title: 'Yext Integrations',
    tier: 'AI',
    summary: 'Provider checklist, preflight diagnostics, and remediation exports for Yext integrations.',
    category: 'SaaS Platform',
    routePath: '/seo/yext-integrations',
    moduleKey: 'yext-integrations',
  },
  {
    title: 'Yext Assist Console',
    tier: 'AI',
    summary: 'Prompt operations console for Yext workflow handoffs and release guidance.',
    category: 'SaaS Platform',
    routePath: '/seo/yext-assist',
    moduleKey: 'yext-assist-console',
  },
  {
    title: 'BrightEdge Readiness Hub',
    tier: 'Core',
    summary: 'Readiness and production gate center for the BrightEdge automation slice.',
    category: 'SaaS Platform',
    routePath: '/seo/brightedge-readiness',
    moduleKey: 'brightedge-readiness-hub',
  },
  {
    title: 'BrightEdge Automation',
    tier: 'Core',
    summary: 'Project, run, schedule, and product orchestration for BrightEdge workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/brightedge-automation',
    moduleKey: 'brightedge-automation',
  },
  {
    title: 'BrightEdge Integrations',
    tier: 'AI',
    summary: 'Provider checklist, preflight diagnostics, and remediation exports for BrightEdge integrations.',
    category: 'SaaS Platform',
    routePath: '/seo/brightedge-integrations',
    moduleKey: 'brightedge-integrations',
  },
  {
    title: 'BrightEdge Assist Console',
    tier: 'AI',
    summary: 'Prompt operations console for BrightEdge workflow handoffs and release guidance.',
    category: 'SaaS Platform',
    routePath: '/seo/brightedge-assist',
    moduleKey: 'brightedge-assist-console',
  },
  {
    title: 'Writesonic Readiness Hub',
    tier: 'Core',
    summary: 'Readiness and production gate center for the Writesonic automation slice.',
    category: 'SaaS Platform',
    routePath: '/seo/writesonic-readiness',
    moduleKey: 'writesonic-readiness-hub',
  },
  {
    title: 'Writesonic Automation',
    tier: 'Core',
    summary: 'Project, run, schedule, and product orchestration for Writesonic workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/writesonic-automation',
    moduleKey: 'writesonic-automation',
  },
  {
    title: 'Writesonic Integrations',
    tier: 'AI',
    summary: 'Provider checklist, preflight diagnostics, and remediation exports for Writesonic integrations.',
    category: 'SaaS Platform',
    routePath: '/seo/writesonic-integrations',
    moduleKey: 'writesonic-integrations',
  },
  {
    title: 'Writesonic Assist Console',
    tier: 'AI',
    summary: 'Prompt operations console for Writesonic workflow handoffs and release guidance.',
    category: 'SaaS Platform',
    routePath: '/seo/writesonic-assist',
    moduleKey: 'writesonic-assist-console',
  },
  {
    title: 'Promptwatch Readiness Hub',
    tier: 'Core',
    summary: 'Readiness and production gate center for the Promptwatch automation slice.',
    category: 'SaaS Platform',
    routePath: '/seo/promptwatch-readiness',
    moduleKey: 'promptwatch-readiness-hub',
  },
  {
    title: 'Promptwatch Automation',
    tier: 'Core',
    summary: 'Project, run, schedule, and product orchestration for Promptwatch workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/promptwatch-automation',
    moduleKey: 'promptwatch-automation',
  },
  {
    title: 'Promptwatch Integrations',
    tier: 'AI',
    summary: 'Provider checklist, preflight diagnostics, and remediation exports for Promptwatch integrations.',
    category: 'SaaS Platform',
    routePath: '/seo/promptwatch-integrations',
    moduleKey: 'promptwatch-integrations',
  },
  {
    title: 'Promptwatch Assist Console',
    tier: 'AI',
    summary: 'Prompt operations console for Promptwatch workflow handoffs and release guidance.',
    category: 'SaaS Platform',
    routePath: '/seo/promptwatch-assist',
    moduleKey: 'promptwatch-assist-console',
  },
  {
    title: 'Neo4j Readiness Hub',
    tier: 'Core',
    summary: 'Readiness and production gate center for Neo4j graph intelligence and runtime wiring.',
    category: 'SaaS Platform',
    routePath: '/seo/neo4j-readiness',
    moduleKey: 'neo4j-readiness-hub',
  },
  {
    title: 'Neo4j Automation',
    tier: 'Core',
    summary: 'Knowledge graph upsert, Cypher execution, and GraphRAG context automation workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/neo4j-automation',
    moduleKey: 'neo4j-automation',
  },
  {
    title: 'Neo4j Integrations',
    tier: 'AI',
    summary: 'Vendor mapping, ecosystem connector coverage, and live Neo4j connectivity probes.',
    category: 'SaaS Platform',
    routePath: '/seo/neo4j-integrations',
    moduleKey: 'neo4j-integrations',
  },
  {
    title: 'SEO.AI Readiness Hub',
    tier: 'Core',
    summary: 'Readiness and production gate center for the SEO.AI automation slice.',
    category: 'SaaS Platform',
    routePath: '/seo/seo-ai-readiness',
    moduleKey: 'seoai-readiness-hub',
  },
  {
    title: 'SEO.AI Automation',
    tier: 'Core',
    summary: 'Project, run, and schedule orchestration for SEO.AI workflows.',
    category: 'SaaS Platform',
    routePath: '/seo/seo-ai-automation',
    moduleKey: 'seoai-automation',
  },
  {
    title: 'SEO.AI Integrations',
    tier: 'AI',
    summary: 'Provider checklist, preflight diagnostics, and remediation exports for SEO.AI integrations.',
    category: 'SaaS Platform',
    routePath: '/seo/seo-ai-integrations',
    moduleKey: 'seoai-integrations',
  },
  {
    title: 'SEO.AI Assist Console',
    tier: 'AI',
    summary: 'Prompt operations console for SEO.AI Assist with workflow handoffs.',
    category: 'SaaS Platform',
    routePath: '/seo/seo-ai-assist',
    moduleKey: 'seoai-assist-console',
  },
  {
    title: 'Ahrefs Command Center',
    tier: 'Core',
    summary: 'Unified Ahrefs parity, provider checklist, production gate, and full automation control surface.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/ahrefs-command-center',
    moduleKey: 'ahrefs-command-center',
  },
  {
    title: 'Surfer Command Center',
    tier: 'Core',
    summary:
      'Unified Surfer parity, provider checklist, wiring plan, setup playbook, production gate, and full automation control surface.',
    category: 'Surfer Core Tools',
    routePath: '/seo/surfer-command-center',
    moduleKey: 'surfer-command-center',
  },
  {
    title: 'Ahrefs Parity: Brand Radar',
    tier: 'Parity',
    summary: 'AI-answer-engine visibility, citations, and sentiment intelligence parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/brand-radar',
    moduleKey: 'ahrefs-brand-radar',
  },
  {
    title: 'Ahrefs Parity: Custom Prompts',
    tier: 'Parity',
    summary: 'Prompt intelligence and custom query tracking parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/custom-prompts',
    moduleKey: 'ahrefs-custom-prompts',
  },
  {
    title: 'Ahrefs Parity: Dashboard',
    tier: 'Parity',
    summary: 'Executive KPI dashboard and multi-module aggregation parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/dashboard',
    moduleKey: 'ahrefs-dashboard',
  },
  {
    title: 'Ahrefs Parity: Site Explorer',
    tier: 'Parity',
    summary: 'Domain intelligence parity for organic, paid, backlink, and competitor snapshots.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/site-explorer',
    moduleKey: 'ahrefs-site-explorer',
  },
  {
    title: 'Ahrefs Parity: Keywords Explorer',
    tier: 'Parity',
    summary: 'Keyword research, clustering, and opportunity scoring parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/keywords-explorer',
    moduleKey: 'ahrefs-keywords-explorer',
  },
  {
    title: 'Ahrefs Parity: Site Audit',
    tier: 'Parity',
    summary: 'Technical crawl and issue remediation parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/site-audit',
    moduleKey: 'ahrefs-site-audit',
  },
  {
    title: 'Ahrefs Parity: Rank Tracker',
    tier: 'Parity',
    summary: 'SERP rank movement, volatility, and forecast parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/rank-tracker',
    moduleKey: 'ahrefs-rank-tracker',
  },
  {
    title: 'Ahrefs Parity: GSC Insights',
    tier: 'Parity',
    summary: 'Search-console-style insight rollups and anomaly detection parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/gsc-insights',
    moduleKey: 'ahrefs-gsc-insights',
  },
  {
    title: 'Ahrefs Parity: Content Explorer',
    tier: 'Parity',
    summary: 'Content discovery and topic gap analysis parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/content-explorer',
    moduleKey: 'ahrefs-content-explorer',
  },
  {
    title: 'Ahrefs Parity: Web Analytics',
    tier: 'Parity',
    summary: 'Realtime traffic analytics and trend reporting parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/web-analytics',
    moduleKey: 'ahrefs-web-analytics',
  },
  {
    title: 'Ahrefs Parity: Bot Analytics',
    tier: 'Parity',
    summary: 'Crawler and bot behavior observability parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/bot-analytics',
    moduleKey: 'ahrefs-bot-analytics',
  },
  {
    title: 'Ahrefs Parity: GBP Monitor',
    tier: 'Parity',
    summary: 'Local business profile and map-rank monitoring parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/gbp-monitor',
    moduleKey: 'ahrefs-gbp-monitor',
  },
  {
    title: 'Ahrefs Parity: Social Media Manager',
    tier: 'Parity',
    summary: 'Cross-network social planning, publishing, and analytics parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/social-media-manager',
    moduleKey: 'ahrefs-social-media-manager',
  },
  {
    title: 'Ahrefs Parity: Portfolios',
    tier: 'Parity',
    summary: 'Multi-site portfolio monitoring and unified KPI portfolio parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/portfolios',
    moduleKey: 'ahrefs-portfolios',
  },
  {
    title: 'Ahrefs Parity: Report Builder',
    tier: 'Parity',
    summary: 'Custom report creation and sharing workflow parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/report-builder',
    moduleKey: 'ahrefs-report-builder',
  },
  {
    title: 'Ahrefs Parity: AI Content Helper',
    tier: 'Parity',
    summary: 'Keyword-guided content planning and drafting parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/ai-content-helper',
    moduleKey: 'ahrefs-ai-content-helper',
  },
  {
    title: 'Ahrefs Parity: AI Content Grader',
    tier: 'Parity',
    summary: 'Content scoring, factuality review, and rewrite guidance parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/ai-content-grader',
    moduleKey: 'ahrefs-ai-content-grader',
  },
  {
    title: 'Ahrefs Parity: Patches',
    tier: 'Parity',
    summary: 'Technical fixes and page-level remediation parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/patches',
    moduleKey: 'ahrefs-patches',
  },
  {
    title: 'Ahrefs Parity: AI Localization',
    tier: 'Parity',
    summary: 'Translation workflow and locale planning parity.',
    category: 'Ahrefs Core Tools',
    routePath: '/seo/ai-localization',
    moduleKey: 'ahrefs-ai-localization',
  },
];

export function getCatalogByRoutePath(routePath: string | undefined): ModuleCatalogEntry | null {
  if (!routePath) return null;
  return SEO_MODULE_CATALOG.find((item) => item.routePath === routePath) ?? null;
}

export function getCatalogByModuleKey(moduleKey: string | undefined): ModuleCatalogEntry | null {
  if (!moduleKey) return null;
  return SEO_MODULE_CATALOG.find((item) => item.moduleKey === moduleKey) ?? null;
}

export function getCatalogBySlug(slug: string | undefined): ModuleCatalogEntry | null {
  if (!slug) return null;
  return SEO_MODULE_CATALOG.find((item) => item.moduleKey === slug || item.routePath.endsWith(`/${slug}`)) ?? null;
}
