[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py tests.py
pythonpath = . ..
addopts = -ra
filterwarnings =
    # Promote deprecations to errors in tests so we catch them early.
    error::DeprecationWarning
