# Generated by Django 5.2.14 on 2026-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IntelligenceProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='bootstrap', max_length=64)),
            ],
            options={'db_table': 'intelligence_probe'},
        ),
    ]
